### ISSUE TITLE
How to call extrinsics?

### ISSUE THREAD

**Issue by kumarg2161** [ajuna-network/Ajuna.NetApi#26]
I am a Unity developer and I was exploring your packages to connect my game to the Polkadot blockchain. I am still a novice when it comes to blockchain. I was able to connect to the chain using our WebSocket URL and was also able to query all the chain state functions - such as block number, account info, etc.
The next task that I need to perform is calling the extrinsic from Unity. Could you please guide me on how to do this using the Ajuna.NetAPI?
Thanks in advance.

**Comment by dimitrispaxinos** [comment]
Hi Ganesh and thank you for your interest in our .NET Toolchain. 

- Regarding the extrinsic execution, you will find a working demo in the [Ajuna.SDK.Demos](https://github.com/ajuna-network/Ajuna.SDK.Demos) repo. 
- If you want to have a look at a working Unity sample, just checkout the [SubstrateNET.UnityDemo](https://github.com/ajuna-network/SubstrateNET.UnityDemo) repo. The _substrate-seminar_ branch included an extrinsic execution as well. 
- If you have time, you can also check our online Subsstrate seminar ['Build .NET and Unity parachain apps'](https://www.youtube.com/watch?v=IAdvCbK0kQI&ab_channel=ParityTech), which will difinitely give you a much better context.

**Comment by kumarg2161** [comment]
Hi Dimitri. Thank you for your prompt response thank you for sharing the above info. I will definitely check it out.
Also, I was wondering if you happen to have any documentation for your packages.

**Comment by kumarg2161** [comment]
@dimitrispaxinos If I run the dotnet command to generate the respective scaffolded projects does it also create the *.dll files that I can import into my Unity project? Could you please confirm? Thank you!

**Comment by dimitrispaxinos** [comment]
@kumarg2161 Yes, exactly, it does generate all necessary DLLs to be used within the Unity project.

**Comment by dimitrispaxinos** [comment]
@kumarg2161 I also created a short video tutorial regarding the necessary files for Unity and how to generate them. 

- [How to generate the necessary .NET projects](https://www.loom.com/share/6dc9a9e0c84f4aafb42aa6f4b0cc914f)
- [How to generate the necessary DLLs for your Unity Project](https://www.loom.com/share/aad526f5cc2941c9a61a4dddc7e62e69)

**Comment by kumarg2161** [comment]
@dimitrispaxinos Thank you so much for providing assistance.
