### ISSUE TITLE
Unable to connect to the node. Error on initializing the SubstrateClientExt.

### ISSUE THREAD

**Issue by kumarg2161** [ajuna-network/Ajuna.NetApi#27]
I used the Ajuna.SDK toolchain to create all the scaffolded projects and dragged all the necessary *.dll files into the plugins folder as instructed. I have created a `SubstrateManager` class to handle/manage all the interactions with the generated classes bundled in the SubstrateClientExt's dll file. Upon initializing the SubstrateClientExt I am running into the following error:

```
MissingMethodException: Method not found: void Ajuna.NetApi.SubstrateClient..ctor(System.Uri)
SubstrateManager.Start () (at Assets/Scripts/SubstrateManager.cs:26)
```

Could someone please help me resolve this? Thank you!

**Comment by kumarg2161** [comment]
@dimitrispaxinos Can you please help me understand the issue here? Thank you!

**Comment by darkfriend77** [comment]
@kumarg2161 happy to help, could you share some more details, like your SubstrateManager, and if possible the repo, which fails?
