### ISSUE TITLE
Unable to make a pallet call

### ISSUE THREAD

**Issue by RostislavLitovkin** [ajuna-network/Ajuna.NetApi#36]
Hello, I have been trying to submit an extrinsic. Could you please help me with what is wrong?

```
           var method = new Method((byte)SelectedPallet.Index, (byte)SelectedCall.Index, Encoding.ASCII.GetBytes(Args));

            var client = new SubstrateClient(new Uri(Preferences.Get("selectedNetwork", "wss://rpc.polkadot.io")), null);
            await client.ConnectAsync();

            Console.WriteLine("Connected");
            await client.Author.SubmitExtrinsicAsync(method, KeysModel.GetAccount(), null, 64);
```

.Index is of type long - so basically a number

Args is of type string

selected network is a local one 127.0.0.1
(If I try to fetch metadata, it works)

GetAccount() code looks like this:

```
public static string GetPublicKey()
        {
            return Preferences.Get("publicKey", "Error - no pubKey");
        }

public static Account GetAccount()
        {
            return Account.Build(
                KeyType.Ed25519,
                Utils.HexToByteArray(Preferences.Get("privateKey", ""), true),
                Utils.HexToByteArray(GetPublicKey(), true));
        }
```

Also here are 2 images that might also help. I am trying to call a custom pallet. First picture is from a wallet app that I am trying to make, the second one is from substrate front end template, where everything works as it should.

<img width="573" alt="Screenshot 2023-02-06 at 20 33 47" src="https://user-images.githubusercontent.com/77352013/217067438-67e144e2-8b6c-421d-b57a-ebb301de0722.png">

<img width="1512" alt="Screenshot 2023-02-06 at 20 32 47" src="https://user-images.githubusercontent.com/77352013/217067258-876228b9-685b-4bf2-bc7f-85a1932b95ac.png">

**Comment by darkfriend77** [comment]
@RostislavLitovkin let me try to help you, so the first thing that I would propose is that you build the SDK for your substrate chain with the Ajuna.SDK (https://github.com/ajuna-network/Ajuna.SDK), will make everything work out of the box.

This will give you all the extrinsic calls prepared, so you don't have to care for them.

This are the steps:

1.  open console. create a directory projectname. and go into that directory
2.  type `dotnet new --install Ajuna.DotNet.Template`
3.  type `dotnet new sln`
4.  type `dotnet new ajuna --sdk_version 0.2.3 --rest_service projectname.RestService --net_api projectname.NetApiExt --rest_client projectname.RestClient --metadata_websocket ws://127.0.0.1:9944 --force --allow-scripts yes`

Then use the prepared extrinsics,

```
        public async Task<AccountInfo> GetAccountAsync(CancellationToken token)
        {
            if (Account == null || Account.Value == null)
            {
                Log.Warning("No account set!");
                return null;
            }

            return await SubstrateClient.SystemStorage.Account(Account.Value.ToAccountId32(), token);
        }
```

**Comment by darkfriend77** [comment]
`
        public static AccountId32 ToAccountId32(this string address)
        {
            var account32 = new AccountId32();
            account32.Create(address.ToPublicKey());

            return account32;
        }
`

**Comment by Apolixit** [comment]
Hey @RostislavLitovkin ,
As Cedric explained, you can use the SDK to generate your extrinsic pallet calls.

In the code you show us, be careful you don't specified the second argument in Substrate Client constructor.

``` c#
var client = new SubstrateClient(
    new Uri(Preferences.Get("selectedNetwork", "wss://rpc.polkadot.io")), 
    ChargeTransactionPayment.Default()
);

```

Hope it helps :)

**Comment by RostislavLitovkin** [comment]
Thanks very much for your help. You have done a truly amazing work!

I was able to get the balance and make a successful transfer ^^.
