### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by nathanwhit** [ajuna-network/Ajuna.NetApi#4]
Firstly, thank you for all of your work on this library! 

I'm looking at using this library for a project but I'm struggling a bit in figuring out how to use it. I think an example that showed how to (for instance) load a signer, compose and sign an extrinsic, and submit the extrinsic to a chain would be very helpful. As a reference, the examples in [py-substrate-interface](https://github.com/polkascan/py-substrate-interface#create-and-send-signed-extrinsics) do a good job at this.

**Comment by kilogold** [comment]
That would be nice. 
In the meantime, I would recommend checking the Unit-Tests. 
It has all the sample code needed to get started. There are some missing details at times, but you can sort of figure most things out by cross-referencing Substrate documentation. Most of the API is basically an RPC wrapper, so you can test your messages via direct RPC, then try to replicate via C# API.

I know it's not exactly what you're looking for, but it's something to help you while the team has a chance to mature the repository.

Examples & Tutorials would be a great initial contribution idea.
